version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: "rabbit"
    restart: always

  worker:
    container_name: "worker-consumer-example"
    build: .
    command: npm start
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      - AMQP=${AMQP}
      - INPUT_QUEUE=${INPUT_QUEUE}